task: detection

num_classes: 8
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /mnt/d/RT-DETR/RT-DETR-main/rtdetr_pytorch/dataset/train2017
    ann_file: /mnt/d/RT-DETR/RT-DETR-main/rtdetr_pytorch/dataset/annotations/instances_train2017.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 2
  num_workers: 2
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /mnt/d/RT-DETR/RT-DETR-main/rtdetr_pytorch/dataset/val2017/
    ann_file: /mnt/d/RT-DETR/RT-DETR-main/rtdetr_pytorch/dataset/annotations/instances_val2017.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 2
  num_workers: 2
  drop_last: False